### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-discordapp-module#12]
The following is for the number of languages supported or needs to be supported

- [x] English (@GreenMeteor)
- [x] Japanese (@Felli)
- [x] Chinese (@Felli)
- [x] Spanish (@cavp28)
- [x] German (@Felli)
- [x] Portuguese (@caiqueff)
- [x] Russian (@buslov)
- [x] Korean (@Felli)
- [x] French (@Felli)
- [x] Indonesian (@ArchBlood)
- [ ] Other
> More will be added if asked.

**Comment by cavp28** [comment]
I will add the Spanish translation!

**Comment by Felli** [comment]
Thanks. :+1:

**Comment by WebCrew** [comment]
is german already done if not I`ll do it :)
I can also do Austrian, Swiss and Bavarian lol lol lol

**Comment by Felli** [comment]
I've already added German but you can check it and make changes if needed, as for other languages, the more the merrier. :+1:

**Comment by WebCrew** [comment]
Translation seems to be fine :)
