### ISSUE TITLE
Module only shows “connect” and opens discord site

### ISSUE THREAD

**Issue by ghost** [GreenMeteor/humhub-discordapp-module#17]
Installed everything as per instructions. Module shows my channel and online user (me). There is a button “connect” and that’s it. If I press connect, it will open a new browser screen to logon in again on discord. 
Going back to humbug still shows the connect button...
What have I missed?

**Comment by Felli** [comment]
This is on Discords side, it's an external widget provided by Discord that is all.
This is also explained in the README.md file.

> Note: Discord is an external service that provides the widget that is placed within your HumHub's sidebar.

**Comment by ghost** [comment]
But what is it's use on HumHum then, if you can't use it? I fail to understand.

**Comment by Felli** [comment]
The widget itself is just that, a widget that shows those that are online as well as x number of channels within your Discord, I have no control over this, it's planned to integrate webhooks into the module.

**Comment by WebCrew** [comment]
yeah its quite normal that the widget only point you to the real Discord app.

**Comment by Felli** [comment]
@WebCrew to be exact, it should open up to an invite, that is if you have one available to the public. :+1:

**Comment by Felli** [comment]
With that being explained I will close this up unless you have more questions @martinbeek ?
