### ISSUE TITLE
Selection of theme 

### ISSUE THREAD

**Issue by miztizm** [GreenMeteor/humhub-discordapp-module#26]
Can user select a theme from light to dark ?

**Comment by Felli** [comment]
@devcline use, within the URL of the Discord widget it is possible.
### Example
#### Light themed
```
https://discordapp.com/widget?id={server-id}
```
or
#### Dark themed.
```
https://discordapp.com/widget?id={server-id}&theme=dark
```

**Comment by miztizm** [comment]
i want that the user cant set it by himself. I have a humhub white and humhub black themes on the server. 
well its just a suggestion, no problem thanks

**Comment by Felli** [comment]
Sadly this is impossible for me to do as it's coded into Discord's widget URL itself and I can't do this manually.

**Comment by ArchBlood** [comment]
Would seem that Discord no longer supports light/dark theme in their widget or have disabled this function for some reason, either way, I'm going to lock this for now.
