### ISSUE TITLE
Fixing Admin Index & Widget

### ISSUE THREAD

**Issue by WebCrew** [GreenMeteor/humhub-discordapp-module#5]
There is only one thing left to do now, all other things are working now, I did a huge update.

You have to edit widgets/view/discordframe.php line 11 and put in your own code - then the module is 100% done :)

**Comment by Felli** [comment]
At the moment the main issue would be working the admin panel so that you just have to add a link, but thanks for updating the module. :+1:

**Comment by WebCrew** [comment]
I do not know someone who can help us with it. I only know very little about the Admin Panel settings by myself, I only know the basics. We should look for some examples, but to get it working it will become  a interesting drama lol :)

**Comment by Felli** [comment]
Normally when I don't know something I ask over on stackoverflow. xD

**Comment by WebCrew** [comment]
Sounds good :1st_place_medal: 
Keep me updated pls ;)
