### ISSUE TITLE
This module literally broke my humhub.

### ISSUE THREAD

**Issue by xSynthx** [GreenMeteor/humhub-discordapp-module#9]
I am using humhub version 1.2.2 and upon install of this module, my humhub just constantly shows a page that says "An internal server error occurred." I tried deleting the folder from the modules folder, and it still says ^ I cant go to my admin panel, or nothing.

**Comment by xSynthx** [comment]
I changed the correct file, but I feel like I might have changed the wrong part. You should make the 1st step more detailed, as in the file it says
```php
<iframe src="<?php Url::to(['https://discordapp.com/widget?id=', 'id' => Url::to($this->context->route)]); ?>">
    <?php $this->render($view); ?>
</iframe>
```
Are we supposed to put our id after the `widget?id=idhere` or where it says `'id'`?
I put it after the `widget?id=` the first time, and thats when the error occurred, I then put the id where it says `'id'` and it didnt fix the error.

**Comment by Felli** [comment]
Please note that this module is [under development](https://github.com/GreenVolume/humhub-discordapp-module#under-developement), and is in no way to be used without knowing how to implement the Server ID, and I don't have the time to document how to use this module in it's current state.

**Comment by xSynthx** [comment]
If anyone has this same issue, please check here:
https://github.com/humhub/humhub/issues/2729

**Comment by Felli** [comment]
The module should now be fully operational.
